### ISSUE TITLE
GitHub workflow builds and tests with the wrong Go compiler

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-goer#98]
### Description
Using Dependabot for upgrading the Go compiler is great, but it doesn't take care of the Go compiler reference in the GitHub workflow file:

```yaml
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.17.3"
```

Could we automate this synchronization somehow, or automatically verify that they're the same? If not, just do a one-shot update and try to remember to push an extra commit to the Dependabot branch the next time we upgrade.

### Motivation
We should obviously test with the same compiler that we use for the Docker image builds.

### Exemplification
N/A

### Benefits
Obvious.

### Possible Drawbacks
None.
